version: "3.7"

services:
  nuxt-app:
    build: .
    container_name: melofind_frontend
    restart: always
    ports:
      - "3000:3000"
    command: "yarn dev"
    networks:
      - nuxt-network
networks:
  nuxt-network:
    driver: bridge
 